### PR TITLE
Add reviewer(s) when creating a pull-request

### PR DESCRIPTION
**Pull request by ultr4nerd**
Done! I have already tested it and works perfectly! Let me know if it looks good for you. 

Also, I think that you could open an issue for adding team reviewers to a pull request. It would be a great feature. I know is possible but I'm not sure how to do it the best way possible with bash.

### CODE REVIEW

**Comment by andrii-bodnar** [comment]
@ultr4nerd looks good to me, thanks a lot for your contribution! 🚀 

> I know is possible but I'm not sure how to do it the best way possible with bash.

Could it be a different approach than the current features?

**Review by andrii-bodnar — APPROVED** [review]

**Comment by ultr4nerd** [comment]
@andrii-bodnar Is adding other field to the request, to add teams as reviewers

**Comment by andrii-bodnar** [comment]
@ultr4nerd and it can't be passed with the `requested_reviewers` simultaneously in one request, right?

**Comment by ultr4nerd** [comment]
No, actually it's possible, but I wasn't able to make it work ☹️

**Comment by andrii-bodnar** [comment]
@ultr4nerd let's see if this feature will be requested by Action users and then will try to solve that 🙂

**Pull request merged**
